# Makefile.deps created Thu Jan 16 04:36:39 PST 2020
ubigint.o: ubigint.cpp ubigint.h debug.h relops.h
bigint.o: bigint.cpp bigint.h debug.h relops.h ubigint.h util.h
libfns.o: libfns.cpp libfns.h bigint.h debug.h relops.h ubigint.h
scanner.o: scanner.cpp scanner.h debug.h
debug.o: debug.cpp debug.h util.h bigint.h relops.h ubigint.h
util.o: util.cpp util.h debug.h bigint.h relops.h ubigint.h
main.o: main.cpp bigint.h debug.h relops.h ubigint.h iterstack.h libfns.h \
 scanner.h util.h
